engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
ratings:
   paths:
   - src/**
   - "**.css"
   - "**.js"
   - "**.php"
exclude_paths:
- src/wp-includes/SimplePie/**/*
- tests/**/*
