---
engines:
  rubocop:
    enabled: false
  coffeelint:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.css"
  - "**.php"
exclude_paths:
- build/**/*
- node_modules/**/*
- src/wp-includes/SimplePie/**/*
- tests/**/*
- tools/**/*
