build:
  environment:
    php:
      version: 7.0.20
  dependencies:
    before:
      - composer require --dev wp-coding-standards/wpcs:dev-develop
  tests:
    override:
      - phpcs-run
tools:
  php_code_sniffer:
    enabled: true
    config:
      standard: "WordPress-Core"
  php_analyzer:
    enabled: true  
    extensions:
      - php
