build:
  environment:
    php:
      version: 7.0.8
  dependencies:
    before:
      - composer require --dev wp-coding-standards/wpcs:dev-develop
  tests:
    override:
      - phpcs-run
tools:
  php_code_sniffer:
    enabled: true
    config:
      standard: "WordPress-Core"
  php_cs_fixer: true 
  php_analyzer:
    enabled: true  
    extensions:
      - php
filter:
  paths: [src/*]
  excluded_paths:
        - "vendor/*," 
        - "build/*,"
        - "node_modules/*,"
        - "/src/wp-admin/includes/class-ftp*"
        - "/src/wp-admin/includes/class-ftp*"
        - "/src/wp-admin/includes/class-pclzip.php"
        - "/src/wp-admin/includes/deprecated.php"
        - "/src/wp-admin/includes/ms-deprecated.php"
        - "/src/wp-includes/atomlib.php"
        - "/src/wp-includes/class-IXR.php"
        - "/src/wp-includes/class-json.php"
        - "/src/wp-includes/class-phpass.php"
        - "/src/wp-includes/class-phpmailer.php"
        - "/src/wp-includes/class-pop3.php"
        - "/src/wp-includes/class-requests.php"
        - "/src/wp-includes/class-simplepie.php"
        - "/src/wp-includes/class-smtp.php"
        - "/src/wp-includes/class-snoopy.php"
        - "/src/wp-includes/deprecated.php"
        - "/src/wp-includes/ms-deprecated.php"
        - "/src/wp-includes/pluggable-deprecated.php"
        - "/src/wp-includes/rss.php"
        - "/src/wp-includes/ID3/*"
        - "/src/wp-includes/IXR/*"
        - "/src/wp-includes/random_compat/*"
        - "/src/wp-includes/Requests/*"
        - "/src/wp-includes/SimplePie/*"
        - "/src/wp-includes/Text/*"
        - "/tests/*"
        - "/tools/*"
