language: php
php:
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction --dev

script:
  # - vendor/bin/phpunit
  - vendor/bin/phpcs  --standard=phpcs.xml.dist --report-summary --report-source
  - vendor/bin/phpcbf  --standard=phpcs.xml.dist --report-summary --report-source
