sudo: false
language: php
matrix:
  include:
  - php: 5.5
    env: WP_TRAVISCI=travis:js
  - php: 5.2
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.3
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.4
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.5
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.6
    env: WP_TRAVISCI=travis:phpunit
  - php: hhvm
    env: WP_TRAVISCI=travis:phpunit
  allow_failures:
  - php: hhvm
  fast_finish: true
before_install:
- WP_CORE_DIR=/tmp/wordpress/
- |
  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
      mysql -e "CREATE DATABASE wordpress_tests;" -uroot
      cp wp-tests-config-sample.php wp-tests-config.php
      sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
      sed -i "s/yourusernamehere/travis/" wp-tests-config.php
      sed -i "s/yourpasswordhere//" wp-tests-config.php
      svn checkout https://plugins.svn.wordpress.org/wordpress-importer/trunk tests/phpunit/data/plugins/wordpress-importer
  fi
before_script:
- npm install -g grunt-cli
- npm install
script: grunt $WP_TRAVISCI
notifications:
  slack:
    secure: eL9NX6Q1PUUfEeLSrvWka5+uLSFBAhMFAkLTm2/iOcLb8MfGp1pVYpgfZFB6Gi1rmlSk1IDtCsLU1+CYpVrQhIXyur3Ryfm5WFXr51UmCIeMfd+g4jCRw3RK0LTpfAQUcav4DPabphKvI+S1CYdvWFINb/TvbbqGpQIQ/srb8PM=
