# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP versions to test against
php:
    - "5.2"
    - "5.3"
    - "5.4"
    - "5.5"

# Build environment variables
env:
    - WP_TRAVISCI="qunit:compiled"
    - WP_TRAVISCI="jshint"
    - WP_TRAVISCI="phpunit"

# Build matrix options
matrix:
  include:
    - php: "5.6"
    - php: "hhvm"
  allow_failures:
    - php: "5.6"
    - php: "hhvm"
  fast_finish: true

# Before install, any failures here will return the build 'errored'
before_install:
    - WP_CORE_DIR=/tmp/wordpress/

# After install, any failures here will return the build 'errored'
# See upstream issue https://github.com/travis-ci/travis-ci/issues/2332
# after_install:
  - >
    if [[ "$WP_TRAVISCI" == "phpunit" ]]; then
        mysql -e "CREATE DATABASE wordpress_tests;" -uroot
        cp wp-tests-config-sample.php wp-tests-config.php
        sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
        sed -i "s/yourusernamehere/travis/" wp-tests-config.php
        sed -i "s/yourpasswordhere//" wp-tests-config.php
        svn checkout https://plugins.svn.wordpress.org/wordpress-importer/trunk tests/phpunit/data/plugins/wordpress-importer
    fi

# Before script, any failures here will return the build 'failed'
before_script:

    - npm install -g grunt-cli
    - npm install

script: grunt $WP_TRAVISCI
