language: php
php:
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction --dev
  - composer update --lock

script:
    - export XMLLINT_INDENT="	"
    - xmllint --noout phpcs.xml.dist
    - xmllint --format phpcs.xml.dist
  # - vendor/bin/phpunit
  - vendor/bin/phpcs  --standard=phpcs.xml.dist --report-summary --report-source
  # - vendor/bin/phpcbf  --standard=phpcs.xml.dist --report-summary --report-source
  - composer run-script lint
  # - composer run-script format
  - vendor/bin/phpcs 
  # - vendor/bin/phpcbf 
  - ./vendor/bin/phpcs 
  - ./vendor/bin/phpcbf 
  # - ./vendor/bin/phpcs -i
  # - ./vendor/bin/phpcbf -vvv
  # - ./vendor/bin/phpcs -p . --standard=PHPCompatibility
  # - ./vendor/bin/phpcs -p . --standard=WordPress
  # - ./vendor/bin/phpcs -p . --standard=WordPress-Core
  - ./vendor/bin/phpcs --standard=phpcs.xml.dist
  - ./vendor/bin/phpcbf -p . --standard=WordPress --report=summary
