# https://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 8.9.3

clone_depth: 3

branches:
    only:
      - master

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm -g
  - npm install


test_script:
  - node --version
  - npm --version
  - cmd: "grunt build"
